const perfumes = [
    // ===== MASCULINOS =====
    {
        id: 1,
        nome: "Asad",
        marca: "Lattafa",
        categoria: "amadeirado",
        genero: "Masculino",
        preco: 219.90,
        descricao: "O perfume árabe masculino mais vendido do Brasil. Amadeirado adocicado com baunilha, pimenta e couro.",
        inspirado: "Inspirado no Dior Sauvage Elixir",
        nota: 4.8,
        avaliacoes: 214,
        fixacao: "Muito Alta",
        badge: "Mais Vendido",
        emoji: "🦁",
        imagem: "images/Masculino/asad.webp",
    },
    {
        id: 2,
        nome: "Club de Nuit Intense Man",
        marca: "Armaf",
        categoria: "amadeirado",
        genero: "Masculino",
        preco: 249.90,
        descricao: "Frutado, esfumaçado e amadeirado. O produto que mais converte venda por impulso.",
        inspirado: "Inspirado no Creed Aventus",
        nota: 4.9,
        avaliacoes: 342,
        fixacao: "Muito Alta",
        badge: "Top Vendas",
        emoji: "🍍",
        imagem: "images/Masculino/Club de Nuit Intense Man.webp",
    },
    {
        id: 3,
        nome: "Hawas For Him",
        marca: "Rasasi",
        categoria: "citrico",
        genero: "Masculino",
        preco: 279.90,
        descricao: "Aquático e fresco com ameixa, maçã e canela. Ideal para o clima brasileiro e verão.",
        inspirado: "Inspirado no Versace Pour Homme",
        nota: 4.7,
        avaliacoes: 158,
        fixacao: "Alta",
        badge: "",
        emoji: "🌊",
        imagem: "images/Masculino/Hawas For Him.webp",
    },
    {
        id: 4,
        nome: "Oud for Glory",
        marca: "Lattafa",
        categoria: "oud",
        genero: "Masculino",
        preco: 229.90,
        descricao: "Saffron, oud, lavanda e almíscar. Oud acessível com assinatura forte duradoura.",
        inspirado: "Inspirado no Initio Oud for Greatness",
        nota: 4.6,
        avaliacoes: 121,
        fixacao: "Muito Alta",
        badge: "",
        emoji: "🌿",
        imagem: "images/Masculino/Oud for Glory.webp",
    },
    {
        id: 5,
        nome: "Salvo",
        marca: "Maison Alhambra",
        categoria: "citrico",
        genero: "Masculino",
        preco: 189.90,
        descricao: "O mais versátil, na pegada do Sauvage. Fresco e fácil de usar para o dia e trabalho.",
        inspirado: "Inspirado no Dior Sauvage",
        nota: 4.6,
        avaliacoes: 142,
        fixacao: "Média",
        badge: "Custo-Benefício",
        emoji: "💧",
        imagem: "images/Masculino/Salvo.webp",
    },
    {
        id: 6,
        nome: "L'Aventure",
        marca: "Al Haramain",
        categoria: "citrico",
        genero: "Masculino",
        preco: 299.90,
        descricao: "A opção premium de dupe do Aventus. Considerado o mais fiel ao original.",
        inspirado: "Inspirado no Creed Aventus",
        nota: 4.7,
        avaliacoes: 88,
        fixacao: "Alta",
        badge: "Premium",
        emoji: "🍋",
        imagem: "images/Masculino/L'Aventure.webp",
    },
    {
        id: 7,
        nome: "Asad Elixir",
        marca: "Lattafa",
        categoria: "oud",
        genero: "Masculino",
        preco: 259.90,
        descricao: "Evolução concentrada do Asad. Especiarias, tabaco e baunilha. Presença marcante.",
        inspirado: "Inspirado no Beau de Jour (Tom Ford)",
        nota: 4.7,
        avaliacoes: 63,
        fixacao: "Extrema",
        badge: "",
        emoji: "⚡",
        imagem: "images/Masculino/Asad Elixir.webp",
    },
    {
        id: 8,
        nome: "Raghba",
        marca: "Lattafa",
        categoria: "amadeirado",
        genero: "Masculino",
        preco: 159.90,
        descricao: "O porta de entrada perfeito. Doce, quente e acessível para iniciantes.",
        inspirado: "",
        nota: 4.4,
        avaliacoes: 143,
        fixacao: "Alta",
        badge: "Custo-Benefício",
        emoji: "🔥",
        imagem: "images/Masculino/Raghba.webp",
    },
    {
        id: 9,
        nome: "Fakhar Black",
        marca: "Lattafa",
        categoria: "amadeirado",
        genero: "Masculino",
        preco: 199.90,
        descricao: "Maçã, lavanda, incenso e couro. Sofisticado e elegante para noites especiais.",
        inspirado: "Inspirado no Parfums de Marly Layton",
        nota: 4.5,
        avaliacoes: 96,
        fixacao: "Alta",
        badge: "",
        emoji: "🖤",
        imagem: "images/Masculino/Fakhar Black.webp",
    },
    {
        id: 10,
        nome: "Turathi Blue",
        marca: "Afnan",
        categoria: "citrico",
        genero: "Masculino",
        preco: 269.90,
        descricao: "Blue moderno, fresco e elegante. Perfeito para o dia a dia, trabalho e clima quente.",
        inspirado: "Inspirado no Bleu de Chanel",
        nota: 4.7,
        avaliacoes: 81,
        fixacao: "Alta",
        badge: "",
        emoji: "💙",
        imagem: "images/Masculino/Turathi Blue.webp",
    },
    // ===== FEMININOS =====
    {
        id: 11,
        nome: "Yara",
        marca: "Lattafa",
        categoria: "floral",
        genero: "Feminino",
        preco: 189.90,
        descricao: "O perfume árabe feminino mais vendido do Brasil. Doce de baunilha, orquídea e heliotrópio. Febre nas redes.",
        inspirado: "Inspirado no La Vie Est Belle",
        nota: 4.9,
        avaliacoes: 387,
        fixacao: "Muito Alta",
        badge: "Mais Vendido",
        emoji: "🌸",
        imagem: "images/Feminino/Yara.webp",
    },
    {
        id: 12,
        nome: "Sabah Al Ward",
        marca: "Al Wataniah",
        categoria: "floral",
        genero: "Feminino",
        preco: 169.90,
        descricao: "O clássico 'perfume rosa'. Floral oriental com maçã e rosa. Romântico e versátil.",
        inspirado: "Inspirado no Delina (Parfums de Marly)",
        nota: 4.5,
        avaliacoes: 118,
        fixacao: "Alta",
        badge: "",
        emoji: "🌹",
        imagem: "images/Feminino/Sabah Al Ward.webp",
    },
    {
        id: 13,
        nome: "Fakhar Rose",
        marca: "Lattafa",
        categoria: "floral",
        genero: "Feminino",
        preco: 219.90,
        descricao: "O 'perfume da sereia'. Floral de rosa com toque gourmand de baunilha. Elegante e delicado. Frasco azul.",
        inspirado: "Inspirado no Armaf Club de Nuit Woman",
        nota: 4.6,
        avaliacoes: 84,
        fixacao: "Alta",
        badge: "",
        emoji: "🧜‍♀️",
        imagem: "images/Feminino/Fakhar Rose.webp",
    },
    {
        id: 14,
        nome: "Atheeri",
        marca: "Lattafa",
        categoria: "citrico",
        genero: "Feminino",
        preco: 209.90,
        descricao: "O famoso 'perfume da abelha'. Frutado doce e fresco, perfeito para o calor. Ótimo para o dia.",
        inspirado: "",
        nota: 4.7,
        avaliacoes: 95,
        fixacao: "Alta",
        badge: "Viral",
        emoji: "🐝",
        imagem: "images/Feminino/Atheeri.webp",
    },
    {
        id: 15,
        nome: "Mayar",
        marca: "Lattafa",
        categoria: "floral",
        genero: "Feminino",
        preco: 199.90,
        descricao: "Floral elegante e feminino com rosa, peônia e almíscar. Clássico, refinado e versátil.",
        inspirado: "Inspirado no Chance (Chanel)",
        nota: 4.6,
        avaliacoes: 76,
        fixacao: "Alta",
        badge: "",
        emoji: "🌷",
        imagem: "images/Feminino/Mayar.webp",
    },
    {
        id: 16,
        nome: "Nebras",
        marca: "Lattafa",
        categoria: "floral",
        genero: "Feminino",
        preco: 239.90,
        descricao: "Âmbar doce e envolvente com baunilha e cacau. Quente, aconchegante e com rastro marcante.",
        inspirado: "Inspirado no Libre (YSL)",
        nota: 4.6,
        avaliacoes: 102,
        fixacao: "Alta",
        badge: "",
        emoji: "💛",
        imagem: "images/Feminino/Nebras.webp",
    },
    {
        id: 17,
        nome: "Ana Abiyedh Rouge",
        marca: "Lattafa",
        categoria: "floral",
        genero: "Feminino",
        preco: 219.90,
        descricao: "Floral frutado vermelho, doce e charmoso. Muito bem avaliado e agradável para o dia.",
        inspirado: "Inspirado no BR 540 (intenso)",
        nota: 4.7,
        avaliacoes: 88,
        fixacao: "Alta",
        badge: "",
        emoji: "🍓",
        imagem: "images/Feminino/Ana Abiyedh Rouge.webp",
    },
    {
        id: 18,
        nome: "Yara Tous",
        marca: "Lattafa",
        categoria: "floral",
        genero: "Feminino",
        preco: 209.90,
        descricao: "Variação da Yara, igualmente doce e deliciosa. Baunilha cremosa e fixação duradoura.",
        inspirado: "Inspirado no La Vie Est Belle",
        nota: 4.8,
        avaliacoes: 64,
        fixacao: "Alta",
        badge: "",
        emoji: "🩷",
        imagem: "images/Feminino/Yara Tous.webp",
    },
    {
        id: 19,
        nome: "Durrat Al Aroos",
        marca: "Al Wataniah",
        categoria: "floral",
        genero: "Feminino",
        preco: 179.90,
        descricao: "A 'pérola da noiva'. Floral almiscarado delicado e encantador, ideal para ocasiões especiais.",
        inspirado: "Inspirado no Prada Candy",
        nota: 4.5,
        avaliacoes: 71,
        fixacao: "Alta",
        badge: "",
        emoji: "🪷",
        imagem: "images/Feminino/Durrat Al Aroos.webp",
    },
    {
        id: 20,
        nome: "Watani",
        marca: "Al Wataniah",
        categoria: "floral",
        genero: "Feminino",
        preco: 189.90,
        descricao: "Frutal oriental doce na medida certa, com brilho floral e final almiscarado. Luxuoso e feminino.",
        inspirado: "",
        nota: 4.6,
        avaliacoes: 66,
        fixacao: "Alta",
        badge: "",
        emoji: "💎",
        imagem: "images/Feminino/Watani.webp",
    },
    // ===== UNISSEX =====
    {
        id: 21,
        nome: "Khamrah",
        marca: "Lattafa",
        categoria: "floral",
        genero: "Unissex",
        preco: 259.90,
        descricao: "Gourmand especiado com canela, tâmara, baunilha e tonka. Quente e envolvente para noites frias.",
        inspirado: "Inspirado no Angels' Share (Kilian)",
        nota: 4.9,
        avaliacoes: 256,
        fixacao: "Muito Alta",
        badge: "Tendência",
        emoji: "🥃",
        imagem: "images/Unissex/Khamrah.webp",
    },
    {
        id: 22,
        nome: "Bade'e Al Oud Amethyst",
        marca: "Lattafa",
        categoria: "oud",
        genero: "Unissex",
        preco: 219.90,
        descricao: "Rosa búlgara, oud, baunilha e almíscar. Doce-almiscarado e sedutor, agrada ambos os públicos.",
        inspirado: "Inspirado no Baccarat Rouge 540",
        nota: 4.8,
        avaliacoes: 167,
        fixacao: "Alta",
        badge: "Premium",
        emoji: "💜",
        imagem: "images/Unissex/Bade'e Al Oud Amethyst.webp",
    },
    {
        id: 23,
        nome: "Liquid Brun",
        marca: "French Avenue",
        categoria: "amadeirado",
        genero: "Unissex",
        preco: 399.90,
        descricao: "O rei do momento. Canela, flor de laranjeira, baunilha e pralinê. Doce e refinado.",
        inspirado: "Inspirado no Althair (Parfums de Marly)",
        nota: 4.9,
        avaliacoes: 89,
        fixacao: "Muito Alta",
        badge: "Top 2026",
        emoji: "👑",
        imagem: "images/Unissex/Liquid Brun.webp",
    },
    {
        id: 24,
        nome: "Asad Bourbon",
        marca: "Lattafa",
        categoria: "amadeirado",
        genero: "Unissex",
        preco: 249.90,
        descricao: "O campeão de fixação. Âmbar e baunilha premium com especiarias quentes. Doce e marcante.",
        inspirado: "Inspirado no Tom Ford Noir Extreme",
        nota: 4.8,
        avaliacoes: 175,
        fixacao: "Extrema",
        badge: "Top Fixação",
        emoji: "🥃",
        imagem: "images/Unissex/Asad Bourbon.webp",
    },
    {
        id: 25,
        nome: "Shaghaf Oud",
        marca: "Swiss Arabian",
        categoria: "oud",
        genero: "Unissex",
        preco: 459.90,
        descricao: "Lenda moderna do oud doce. Potência e fixação extremas, mais de 12 horas na pele.",
        inspirado: "",
        nota: 4.7,
        avaliacoes: 67,
        fixacao: "Extrema",
        badge: "Premium",
        emoji: "🕋",
        imagem: "images/Unissex/Shaghaf Oud.webp",
    },
    {
        id: 26,
        nome: "Royal Amber",
        marca: "Orientica",
        categoria: "floral",
        genero: "Unissex",
        preco: 389.90,
        descricao: "Extrait de Parfum de luxo. Frutas exóticas, melão e abacaxi com fundo ambarado. Rastro irresistível.",
        inspirado: "Inspirado no BR 540 Extrait",
        nota: 4.7,
        avaliacoes: 59,
        fixacao: "Extrema",
        badge: "Luxo",
        emoji: "👑",
        imagem: "images/Unissex/Royal Amber.webp",
    },
    {
        id: 27,
        nome: "Detour Noir",
        marca: "Al Haramain",
        categoria: "amadeirado",
        genero: "Unissex",
        preco: 349.90,
        descricao: "Baunilha e especiarias. Conforto e sedução noturna impressionantes.",
        inspirado: "Inspirado no Layton (Parfums de Marly)",
        nota: 4.6,
        avaliacoes: 74,
        fixacao: "Alta",
        badge: "",
        emoji: "🕯️",
        imagem: "images/Unissex/Detour Noir.webp",
    },
    {
        id: 28,
        nome: "Afnan 9PM",
        marca: "Afnan",
        categoria: "floral",
        genero: "Unissex",
        preco: 249.90,
        descricao: "Gourmand sedutor e doce para a noite. Canela, baunilha e flor de laranjeira.",
        inspirado: "Inspirado no Ultramale (JPG)",
        nota: 4.8,
        avaliacoes: 132,
        fixacao: "Muito Alta",
        badge: "Noite",
        emoji: "🌙",
        imagem: "images/Unissex/Afnan 9PM.webp",
    },
    {
        id: 29,
        nome: "Honor & Glory",
        marca: "Lattafa",
        categoria: "floral",
        genero: "Unissex",
        preco: 279.90,
        descricao: "Gourmand intenso com baunilha, rosa e notas doces marcantes. Quente e envolvente.",
        inspirado: "Inspirado no Initio Oud for Greatness",
        nota: 4.7,
        avaliacoes: 92,
        fixacao: "Muito Alta",
        badge: "",
        emoji: "🏅",
        imagem: "images/Unissex/Honor & Glory.webp",
    },
    {
        id: 30,
        nome: "Supremacy Not Only Intense",
        marca: "Afnan",
        categoria: "amadeirado",
        genero: "Unissex",
        preco: 329.90,
        descricao: "Assinatura marcante com performance forte para noite e meia-estação. Estilo sério e impactante.",
        inspirado: "Inspirado no Creed Aventus",
        nota: 4.8,
        avaliacoes: 77,
        fixacao: "Muito Alta",
        badge: "",
        emoji: "⚜️",
        imagem: "images/Unissex/Supremacy Not Only Intense.webp",
    }
];
